# Generated by Django 5.0.2 on 2024-03-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='productos',
        ),
    ]
