# Generated by Django 5.0.2 on 2024-03-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_solicitudcompra_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='precio_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
