# Generated by Django 5.0.2 on 2024-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_solicitudcompra_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
